# Paste this file into `rails credentials:edit` following the secret key.
# Be sure to use the right environment if more than one environment is used
# on a repo.

# Used for Slack notifications
# slack:
#   token: "abcdefghijklmnopqrstuvwxyz"

# Used for email inbox receving integration
# email:
#   email: "myemail@gmail.com"
#   name: "inbox"
#   port: 993
#   host: "imap.gmail.com"
#   ssl: true
#   oauth:
#     site: "https://accounts.google.com"
#     authorize_url: "/o/oauth2/auth"
#     token_url: "/o/oauth2/token"
#     refresh_token: "abcdefghijklmnopqrstuvwxyz"
#     client_id: "abcdefghijklmnopqrstuvwxyz"
#     client_secret: "abcdefghijklmnopqrstuvwxyz"
#   password: "abcdefghijklmnopqrstuvwxyz"  # alternative to oauth
