# Paste this file into `rails credentials:edit` following the secret key.
# Be sure to use the right environment if more than one environment is used
# on a repo.

# Used for Slack notifications
# slack:
#   token: "abcdefghijklmnopqrstuvwxyz"

# Used for email inbox receving integration
# email:
#   email: "myemail@gmail.com"
#   name: "inbox"
#   port: 993
#   ssl: true
#   refresh_token: "abcdefghijklmnopqrstuvwxyz"
#   client_id: "abcdefghijklmnopqrstuvwxyz"
#   client_secret: "abcdefghijklmnopqrstuvwxyz"
#   client_secret_test: "abcdefghijklmnopqrstuvwxyz"
