development:
  charset_table: "0..9, A..Z->a..z, _, a..z"
  sql_sock: /var/run/mysqld/mysqld.sock

staging:
  charset_table: "0..9, A..Z->a..z, _, a..z"
  pid_file: <%= "#{Rails.root}/../pids/searchd.pid %>
  indices_location: <%= "#{Rails.root}/../shared/sphinx %>
  configuration_file: <%= "#{Rails.root}/config/staging.sphinx.conf %>
  binlog_path: <%= "#{Rails.root}/../shared/binlog %>
  sql_sock: /var/run/mysqld/mysqld.sock

production:
  charset_table: "0..9, A..Z->a..z, _, a..z"
  pid_file: <%= "#{Rails.root}/../pids/searchd.pid %>
  indices_location: <%= "#{Rails.root}/../shared/sphinx %>
  configuration_file: <%= "#{Rails.root}/config/production.sphinx.conf %>
  binlog_path: <%= "#{Rails.root}/../shared/binlog %>
  sql_sock: /var/run/mysqld/mysqld.sock
