development:
  charset_table: "0..9, A..Z->a..z, _, a..z"
  sql_sock: /var/run/mysqld/mysqld.sock

staging:
  charset_table: "0..9, A..Z->a..z, _, a..z"
  pid_file: <%= ENV['SPHINX_PID'] %>
  indices_location: <%= Rails.root.join("db/sphinx/staging") %>
  binlog_path: <%= Rails.root.join("log/staging.searchd.binlog") %>
  socket: <%= ENV['SPHINX_BIND'] %>

production:
  charset_table: "0..9, A..Z->a..z, _, a..z"
  pid_file: <%= ENV['SPHINX_PID'] %>
  indices_location: <%= Rails.root.join("db/sphinx/production") %>
  binlog_path: <%= Rails.root.join("log/production.searchd.binlog") %>
  socket: <%= ENV['SPHINX_BIND'] %>
